-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.
CREATE OR REPLACE FUNCTION public.handle_new_user() RETURNS trigger LANGUAGE 'plpgsql' VOLATILE SECURITY DEFINER COST 100 AS $BODY$
declare is_admin boolean;
begin
insert into public.profiles (id)
values (new.id);
-- select count(*) = 1
-- from auth.users into is_admin;
insert into public.user_roles (user_id, role)
values (new.id, 'viewer');
return new;
end;
$BODY$;
-- trigger the function every time a user is created
create trigger on_auth_user_created
after
insert on auth.users for each row execute procedure public.handle_new_user();